# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_remove_youth_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='youth',
            name='rank',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
