# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_youth_rank'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='YouthNote',
            new_name='Note',
        ),
    ]
