# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_auto_20170118_0025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='static/pic_folder/event'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='image',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/volunteer'),
        ),
        migrations.AlterField(
            model_name='youth',
            name='image',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='static/pic_folder/youth'),
        ),
    ]
