# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0017_auto_20170118_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='image',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='members/static/pic_folder/youth'),
        ),
    ]
