# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 05:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20170123_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registeration_link',
            field=models.CharField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
