version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/www/tamkeen
permissions:
  - object: /home/ubuntu/www
    pattern: "**"
    mode: 777
  - object: /home/ubuntu/www/tamkeen/scripts
    pattern: "*.sh"
    mode: 777
hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      timeout: 6000
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 6000
      runas: root
    - location: scripts/migrate.sh
      timeout: 6000
      runas: ubuntu
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: root
  ApplicationStop:
    - location: scripts/stop_application.sh
      timeout: 6000
      runas: root
