# Generated by Django 2.0.6 on 2018-09-13 05:32

import datetime
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = False

    dependencies = [
        ('members','0001_initial'),
    ]

    operations = [

        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date_time', models.DateTimeField()),
                ('fees', models.IntegerField(default=0)),
                ('location', models.CharField(blank=True, max_length=8000)),
                ('image', models.ImageField(default='event/default.png', upload_to='events')),
            ],
        ),
    ]
