# Generated by Django 2.0.6 on 2018-09-11 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_auto_20180909_0933'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='event/default.png', upload_to='books')),
            ],
        ),
        migrations.RemoveField(
            model_name='familymembers',
            name='family',
        ),
        migrations.DeleteModel(
            name='Family',
        ),
        migrations.DeleteModel(
            name='FamilyMembers',
        ),
    ]
