# Generated by Django 2.0.6 on 2018-09-17 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_eventregistration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
    ]
