# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-13 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_answer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default='2017-1-1', max_length=8),
            preserve_default=False,
        ),
    ]
