# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(default='M', max_length=1),
        ),
    ]
