# Generated by Django 2.0.6 on 2018-09-11 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_remove_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='date',
            new_name='datetime',
        ),
    ]
