# Generated by Django 2.0.6 on 2018-09-11 03:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_auto_20180910_2033'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='datetime',
            new_name='date_time',
        ),
    ]
