# Generated by Django 2.0.6 on 2018-09-25 03:10

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_eventregistration_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='full_name',
            new_name='family_name',
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='family_id',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='eventregistration',
            name='people',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100), size=10), default=list, size=10),
            preserve_default=False,
        ),
    ]
