# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-14 14:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_profile_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='c:', upload_to='profile_pics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='uw_waiver',
            field=models.ImageField(default='c', upload_to='waive_forms'),
            preserve_default=False,
        ),
    ]
