# Generated by Django 2.0.6 on 2018-09-13 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_auto_20180910_2034'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fees',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='event/default.png', upload_to='events'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.CharField(blank=True, max_length=8000),
        ),
    ]
