# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 04:35
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20171016_0431'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_page', models.ImageField(default='books/default.png', upload_to='books')),
                ('category', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(default='A', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='BookCheckoutRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book', to='members.Book')),
            ],
        ),
        migrations.AlterField(
            model_name='profile',
            name='photo',
            field=models.ImageField(default='profile_pics/default.png', upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='uw_waiver',
            field=models.ImageField(default='uw_waivers/default.png', upload_to='uw_waivers'),
        ),
        migrations.AddField(
            model_name='bookcheckoutrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
