# Generated by Django 2.0.6 on 2018-09-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_auto_20180924_2012'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventregistration',
            old_name='people',
            new_name='participants',
        ),
    ]
