# Generated by Django 2.0.6 on 2018-09-29 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_auto_20180924_2125'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='number_of_tickets',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='participants',
        ),
        migrations.AddField(
            model_name='eventparticipant',
            name='EventRegistration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registration', to='members.EventRegistration'),
        ),
    ]
