# Generated by Django 2.0.6 on 2018-09-30 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_auto_20180929_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventparticipant',
            name='EventRegistration',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.EventRegistration'),
        ),
        migrations.AlterField(
            model_name='eventparticipant',
            name='gender',
            field=models.CharField(max_length=6),
        ),
    ]
