# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 05:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_book_number_of_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookCheckoutRequest',
            new_name='BookReserve',
        ),
    ]
