# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-17 23:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_auto_20170117_0446'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('address', models.CharField(max_length=100)),
                ('image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date_of_birth', models.DateTimeField()),
                ('gender', models.CharField(max_length=1)),
                ('email', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=100)),
                ('interests', models.CharField(max_length=1000)),
                ('skills', models.CharField(max_length=1000)),
                ('image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder')),
            ],
        ),
        migrations.CreateModel(
            name='YouthNote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youth_id', models.IntegerField()),
                ('note', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='youth',
            old_name='age',
            new_name='rank',
        ),
        migrations.AddField(
            model_name='youth',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='youth',
            name='date_of_birth',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='youth',
            name='email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='gender',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='guardian_email',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='guardian_phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='interests',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='phone',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='youth',
            name='skills',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
    ]
