# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-18 00:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0012_auto_20170117_2357'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='youth',
            name='rank',
        ),
    ]
