# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_profile_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='file',
            field=models.FileField(default='', upload_to='books'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(default='en', max_length=2),
        ),
        migrations.AddField(
            model_name='book',
            name='page_num',
            field=models.IntegerField(default=0),
        ),
    ]
