# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 17:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_auto_20171023_1658'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='file',
            new_name='book_file',
        ),
    ]
