# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0016_auto_20171031_1909'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewMemberRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('gender', models.CharField(default='M', max_length=1)),
                ('whats_app', models.CharField(blank=True, max_length=20)),
                ('email', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
