# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-19 00:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0018_auto_20170118_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image',
            field=models.ImageField(default='pic_folder/no-img.jpg', upload_to='members/static/pic_folder/event'),
        ),
    ]
