# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 21:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_auto_20171108_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='available',
            new_name='hardcopy_available',
        ),
    ]
