# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 05:00
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_auto_20171108_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(verbose_name='Inquiry')),
                ('prize', models.CharField(blank=True, max_length=200)),
                ('pic', models.ImageField(default='awards/default.png', upload_to='awards')),
            ],
        ),
        migrations.CreateModel(
            name='UserAward',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award', to='members.Award')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='award_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
