# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-27 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_auto_20170126_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='youth',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='youth',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1),
        ),
    ]
