# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_award_useraward'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraward',
            name='description',
            field=models.TextField(default=' '),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='award',
            name='description',
            field=models.TextField(),
        ),
    ]
