# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20171110_2141'),
    ]

    operations = [
      
    ]
