# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import embed_video.fields


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20171110_2141'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestedVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', embed_video.fields.EmbedVideoField()),
            ],
        ),
        migrations.AlterField(
            model_name='inquiry',
            name='text',
            field=models.TextField(verbose_name='Message'),
        ),
    ]
