# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-31 17:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0023_auto_20170127_2350'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Note',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.AddField(
            model_name='event',
            name='Album',
            field=models.ImageField(default='no-img.jpg', upload_to='event'),
        ),
        migrations.AddField(
            model_name='event',
            name='flyer',
            field=models.ImageField(default='no-img.jpg', upload_to='event'),
        ),
        migrations.AlterField(
            model_name='youth',
            name='image',
            field=models.ImageField(default='no-img.jpg', upload_to='youth'),
        ),
    ]
