# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_auto_20170131_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='no-img.jpg', upload_to='event')),
            ],
        ),
        migrations.RemoveField(
            model_name='event',
            name='Album',
        ),
        migrations.AddField(
            model_name='eventimages',
            name='event_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.Event'),
        ),
    ]
