# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_suggestedvideo_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suggestedvideo',
            name='video',
            field=models.CharField(max_length=500),
        ),
    ]
