# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_auto_20170201_0002'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventimages',
            old_name='event_id',
            new_name='event',
        ),
    ]
