# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20170201_0007'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventimages',
            name='description',
            field=models.CharField(default=0, max_length=1000),
            preserve_default=False,
        ),
    ]
