# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-01 19:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0026_auto_20171129_2226'),
    ]

    operations = [
        migrations.AddField(
            model_name='inquiry',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
