# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_eventimages_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='names',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
