# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-04 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_checkout'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newmemberrequest',
            name='whats_app',
        ),
        migrations.AddField(
            model_name='newmemberrequest',
            name='phone',
            field=models.CharField(blank=True, max_length=10, verbose_name='Phone Number'),
        ),
    ]
