# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 00:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_event_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='names',
        ),
    ]
