# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-01 21:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_remove_event_names'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventimages',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='members.Event'),
        ),
    ]
