# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_auto_20170201_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
