# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 22:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_event_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Competiton',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('date_time', models.DateTimeField()),
            ],
        ),
    ]
