# Generated by Django 2.0 on 2018-02-14 16:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0031_auto_20180208_1503'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='date_time',
        ),
        migrations.AddField(
            model_name='quiz',
            name='date_time',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='suggestedvideo',
            name='views',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
