# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-18 22:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_competiton'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competiton',
            new_name='Competition',
        ),
    ]
