# Generated by Django 2.0 on 2018-02-15 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_auto_20180214_0819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=10)),
                ('text', models.CharField(max_length=1000)),
                ('date_time', models.DateTimeField()),
                ('dismissed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='whats_app',
            new_name='phone',
        ),
        migrations.AddField(
            model_name='alert',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
