# Generated by Django 2.0 on 2018-02-25 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0033_auto_20180214_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='show_name',
            field=models.BooleanField(default=False),
        ),
    ]
