# Generated by Django 2.0 on 2018-02-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0034_answer_show_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answer',
            old_name='show_name',
            new_name='share_with_others',
        ),
    ]
