# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0035_auto_20170224_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='score',
            field=models.IntegerField(default=None),
        ),
    ]
