# Generated by Django 2.0 on 2018-04-30 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0036_auto_20180327_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestedvideo',
            name='description',
            field=models.CharField(blank=True, max_length=8000),
        ),
    ]
