# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-25 05:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_auto_20170224_0828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionanswer',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
