# Generated by Django 2.0 on 2018-05-04 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0038_auto_20180504_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=8000),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=8000),
        ),
    ]
