# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-06 19:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0039_auto_20170225_0513'),
    ]

    operations = [
        migrations.CreateModel(
            name='Khatirah',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=2000)),
                ('image', models.ImageField(default='no-img.jpg', upload_to='khatirah')),
                ('date_time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='KhatirahAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=2000)),
                ('name', models.CharField(max_length=2000)),
                ('date_time', models.DateTimeField()),
                ('score', models.IntegerField(default=0)),
                ('khatirah', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='khatirahAnswers', to='members.Khatirah')),
            ],
        ),
    ]
