# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-07 23:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0040_khatirah_khatirahanswer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='khatirahanswer',
            name='khatirah',
        ),
        migrations.DeleteModel(
            name='Khatirah',
        ),
        migrations.DeleteModel(
            name='KhatirahAnswer',
        ),
    ]
