# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 05:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0042_youth_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='youth',
            old_name='user_name',
            new_name='USERNAME_FIELD',
        ),
    ]
