# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0045_question_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='link',
            field=models.CharField(default=0, max_length=2000),
            preserve_default=False,
        ),
    ]
