# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-05 22:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0046_question_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='interests',
        ),
    ]
