# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-07 12:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0049_auto_20170405_2301'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parent',
            name='name',
        ),
    ]
