# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0050_remove_parent_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='child',
            old_name='date_of_borth',
            new_name='date_of_birth',
        ),
        migrations.AddField(
            model_name='child',
            name='email',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='ethnic',
            field=models.CharField(choices=[('AA', 'African American'), ('NA', 'Native American'), ('AN', 'Alaska Native'), ('A', 'Asian'), ('CW', 'Caucasian/White'), ('HL', 'Hispanic/latino'), ('PI', 'Pacific Islander'), ('O', 'Other')], default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='grade',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='child',
            name='phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='parent',
            name='other_phone',
            field=models.CharField(default=0, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='link',
            field=models.CharField(blank=True, max_length=2000),
        ),
    ]
