# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-11 18:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0051_auto_20170411_1813'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='link',
            new_name='video_link',
        ),
    ]
