# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-13 19:48
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0052_auto_20170411_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistered',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('children', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=6)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Registered', to='members.Event')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent', to='members.Parent')),
            ],
        ),
        migrations.RemoveField(
            model_name='eventimages',
            name='event',
        ),
        migrations.DeleteModel(
            name='EventImages',
        ),
    ]
