# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-18 22:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('members', '0053_auto_20170413_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questionanswer',
            name='name',
        ),
        migrations.AddField(
            model_name='questionanswer',
            name='user',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
